# This formula is auto-generated by the release workflow.
# Do not edit manually — it will be overwritten on the next release.
#
# See: https://github.com/lijunzh/plex-media-organizer
class PlexOrg < Formula
  desc "Organize torrent-downloaded media into Plex-compatible folder structures"
  homepage "https://github.com/lijunzh/plex-media-organizer"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lijunzh/plex-media-organizer/releases/download/v#{version}/plex-org-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/lijunzh/plex-media-organizer/releases/download/v#{version}/plex-org-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/lijunzh/plex-media-organizer/releases/download/v#{version}/plex-org-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/lijunzh/plex-media-organizer/releases/download/v#{version}/plex-org-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install Dir["**/plex-org"].first
  end

  test do
    assert_match "plex-org", shell_output("#{bin}/plex-org --version")
  end
end
